automation:
  alias: B2500PKG Set DOD
  description: ""

  triggers:
    - trigger: state
      entity_id:
        - input_button.b2500_dod_setzen

  conditions: []

  actions:
    - variables:
        speicher: "{{ states('input_select.speicherauswahl') }}"
        dod_payload: "cd=19,md={{ states('input_number.b2500_dod') | int }}"
        all_speicher: "{{ states('input_text.b2500_all') | from_json }}"
        targets: >
          {% if speicher == 'Alle_Speicher' %}
            {{ all_speicher }}
          {% else %}
            {{ [speicher] }}
          {% endif %}

    - repeat:
        for_each: "{{ targets }}"
        sequence:
          - action: script.turn_on
            target:
              entity_id: "script.{{ repeat.item }}_worker"
            data:
              variables:
                payload: "{{ dod_payload }}"
                followup_payload: "cd=01"
                no_check: false

          - delay:
              seconds: 1

  mode: queued
  max: 10

